### ISSUE TITLE
你好，有没有办法添加自定义词库？

### ISSUE THREAD

**Issue by oldcai** [letiantian/ChineseTone#1]
一些错读统计：

词语 正确 错误
金馆长 jinguanzhang jinguanchang
长高 zhanggao changgao
如何长高 ruhezhanggao ruhechanggao
崴脚 waijiao weijiao
内分泌失调 neifenmishitiao neifenmishidiao
脸上长痘痘怎么办 lianshangzhangdoudouzenmeban lianshangchangdoudouzenmeban
水泊梁山 shuipoliangshan shuiboliangshan
桔色 juse jiese
海娜 haina hainuo
爱望着蓝天发呆 aiwangzhelantianfadai aiwangzhuolantianfadai
漂在外面的涿州人 piaozaiwaimiandezhuozhouren piaozaiwaimiandizhuozhouren
心里住着太阳 xinlizhuzhetaiyang xinlizhuzhuotaiyang
金莎 jinsha jinsuo
镜泊湖 jingpohu jingbohu
你是我年少时最美的梦 nishiwonianshaoshizuimeidemeng nishiwonianshaoshizuimeidimeng
暗夜中的亡灵 anyezhongdewangling anyezhongdiwangling
梦娜 mengna mengnuo
财经法规与会计职业道德 caijingfaguiyukuaijizhiyedaode caijingfaguiyuhuijizhiyedaode
脸上长斑 lianshangzhangban lianshangchangban
结伴同行 jiebantongxing jiebantonghang

**Comment by letiantian** [comment]
感谢建议。已经添加该特性。 见文档  https://github.com/letiantian/ChineseTone#添加自己的词库

更新即可。
